setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt extended_glob
setopt equals
setopt prompt_subst
setopt auto_cd
setopt interactivecomments
setopt auto_continue
setopt auto_param_slash
setopt pushd_ignore_dups
export DIRSTACKSIZE=20
setopt auto_pushd

stty -ixon -ixoff

WORDCHARS=${WORDCHARS//[\/]}

zstyle ':completion:*' menu select

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

fe() (
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview "bat --style numbers,changes --color=always --decorations=always {} | head -500"))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
)

fo() (
  IFS=$'\n' out=("$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)")
  key=$(head -1 <<< "$out")
  file=$(head -2 <<< "$out" | tail -1)
  if [ -n "$file" ]; then
    [ "$key" = ctrl-o ] && open "$file" || ${EDITOR:-vim} "$file"
  fi
)


function open_command() {
  nohup xdg-open "$@" &>/dev/null
}

function zreload() {
  local cache="$ZSH_CACHE_DIR"
  autoload -U compinit zrecompile
  compinit -i -d "$cache/zcomp-$HOST"

  for f in ${ZDOTDIR:-~}/.zshrc "$cache/zcomp-$HOST"; do
    zrecompile -p $f && command rm -f $f.zwc.old
  done

  [[ -n "$SHELL" ]] && exec ${SHELL#-} || exec zsh
}

# DISABLE_UNTRACKED_FILES_DIRTY="true"
# source $XDG_CONFIG_HOME/zsh/persent.zsh-theme

_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

eval "$(zoxide init zsh)"

if [[ -n "${terminfo[kcbt]}" ]]; then
  bindkey -M emacs "${terminfo[kcbt]}" reverse-menu-complete
  bindkey -M viins "${terminfo[kcbt]}" reverse-menu-complete
  bindkey -M vicmd "${terminfo[kcbt]}" reverse-menu-complete
fi
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[P' history-substring-search-up
bindkey '^[N' history-substring-search-down
bindkey "^Xa" _expand_alias
autoload -U edit-command-line
